### PR TITLE
Add channel argument to midi output functions

### PR DESCRIPTION
**Pull request by daviesian**
It would be useful to be able to specify the channel for midi output.

Added an optional midi channel argument for note-on, note-off, control, note and play functions.

### CODE REVIEW

**Comment by samaaron** [comment]
Would it be possible to merge Jeff's recent changes with these pull requests so that I don't accidentally break something you fixed if I merged them manually?

**Comment by daviesian** [comment]
I thought I'd already done that. The only commit I'm excluding is the one where I add my own .gitattributes file.

Help?!

**Comment by samaaron** [comment]
Weird - it's just that Github is telling me that this pull request cannot be automatically merged. Did you rebase your commits to be _after_ Jeff's recent commits? That might do the trick...

**Comment by daviesian** [comment]
I could try rebase, but won't that invoke the wrath of the git gods now that I've pushed to github?

Also, doesn't it look like everything's in the right order anyway:

**Comment by daviesian** [comment]
I could try rebase, but won't that invoke the wrath of the git gods now that I've pushed to github?

Also, doesn't it look like everything's in the right order anyway:

**Comment by daviesian** [comment]
(sorry, submitted unfinished message)
...

https://github.com/iandavies1985/midi-clj/network ?

**Comment by samaaron** [comment]
manually merged - thanks for this :-)

**Pull request closed without merging**
